// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Er3MclGmVbxFgAlH7Pxz_nwvQENwCUc',
    appId: '1:582909295950:android:06523690d2fdc76aa6f21f',
    messagingSenderId: '582909295950',
    projectId: 'lsc-freights',
    databaseURL: 'https://lsc-freights-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lsc-freights.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZjN1v7QK5HrfX9WqwGsPQV92tsxg0tCQ',
    appId: '1:582909295950:ios:4bfc1fb7df21b92ea6f21f',
    messagingSenderId: '582909295950',
    projectId: 'lsc-freights',
    databaseURL: 'https://lsc-freights-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lsc-freights.appspot.com',
    iosBundleId: 'com.lsc.app',
  );
}
